#!/usr/bin/ruby

require 'test/unit'
require 'mime/types'

class SmokeTest < Test::Unit::TestCase

  def test_text_plain
    type = MIME::Types['text/plain'].first
    assert_equal 'text', type.media_type
    assert_equal 'plain', type.sub_type
  end

end
